name: CI for Artifact Upload

on:
  push:
    branches:
      - main
  workflow_dispatch:

on:
  workflow_dispatch:
    inputs:
      artifact_file_name:
        description: 'Artifact File Name'
        required: true
        default: '10.10.10.10'
      artifact_type:
        description: 'Artifact Type'
        required: true
        default: 'ga'
      is_marked_latest_dll:
        description: 'Is Marked Latest DLL'
        required: true
        default: 'false'

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Generate env file
      run: |
        echo "Generating env file..."
        export HOME=/home/runner

    - name: Upload artifacts
      run: |
        echo "Uploading artifacts: $ARTIFACT_FILE_NAME, type: $ARTIFACT_TYPE, latest: $IS_MARKED_LATEST_DLL"
      env:
        D42_PWD: "abc123!@#"
        ARTIFACT_FILE_NAME: ${{ github.event.inputs.artifact_file_name }}
        ARTIFACT_TYPE: ${{ github.event.inputs.artifact_type }}
        IS_MARKED_LATEST_DLL: ${{ github.event.inputs.is_marked_latest_dll }}


    - name: Docker Prune
      run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE
        docker stop $(docker ps -aq) || true
        docker system prune -a -f

    - name: Notification on job failure
      if: failure()
      run: echo "Sending failure notification..."
      # Here you can add actual notification actions such as sending an email or slack message

  # Define other jobs if needed

permissions:
  contents: read
  issues: write
